### PR TITLE
Add german message

### PR DESCRIPTION
**Pull request by NicoAiko**
Currently supported is only the English prompt.

I am a German developer so I want this feature for me too 😄 

I couldn't properly test it though, as Hyper didn't load my plugin for some reason...

### CODE REVIEW

**Comment by albertjan** [comment]
Cheers Thanks! 😄

**Comment by NicoAiko** [comment]
You merged it too early... I couldn't test it and it doesn't work for me properly yet.

I found out, that Hyper created a second folder for local plugins so I'm in testing state right now.

If possible, please revert the merge, as I'll provide a fix for it

**Comment by albertjan** [comment]
hah ok 😄

**Comment by albertjan** [comment]
Looked into this some more @NicoAiko?

**Pull request merged**
